# Generated by Django 4.0.1 on 2022-02-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'market',
                'verbose_name_plural': 'markets',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('cagr', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sharpe', models.DecimalField(decimal_places=2, max_digits=3)),
                ('long_only', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('market', models.ManyToManyField(to='catalog.Market')),
            ],
            options={
                'verbose_name': 'strategy',
                'verbose_name_plural': 'strategies',
            },
        ),
    ]
